### ISSUE TITLE
Remastered music

### ISSUE THREAD

**Issue by Keith94** [Clownacy/Cave-Story-Mod-Loader#23]
Any possibility to play Cave Story with remastered music and/or graphics from Cave Story+?

**Comment by Clownacy** [comment]
Yes...? If you read [the](https://www.cavestory.org/forums/threads/dll-mod-loader-ogg-music-mod.13879/) [threads](https://www.cavestory.org/forums/threads/graphics-enhancement-pack-mod.13920/), they show videos of both being used.
