### ISSUE TITLE
Horrible graphics bug when increasing sprite resolution

### ISSUE THREAD

**Issue by Zanmato27** [Clownacy/Cave-Story-Mod-Loader#33]
![doukutsu_2018-10-02_02-57-49](https://user-images.githubusercontent.com/10169555/46333639-12ea4a00-c5ef-11e8-95e3-a3edf851edda.png)
![doukutsu_2018-10-02_02-57-54](https://user-images.githubusercontent.com/10169555/46333640-12ea4a00-c5ef-11e8-97a5-2caa3051c38f.png)

This is taken using the pre-patched English v1.0.0.6 of the game found on the tribute site without any other modifications being applied other than what came with the Mod Loader. This happened with increasing the sprite resolution from 1 to 2.

**Comment by Clownacy** [comment]
You do know what that setting's for, right?

**Comment by Leo40Git** [comment]
If you haven't gotten Clownacy's hint, you're supposed to upscale the graphics yourself. The Mod Loader only makes the game work with the upscaled graphics correctly.

**Comment by Zanmato27** [comment]
And how can I upscale the graphics? Is there anything I need to do that?

**Comment by Leo40Git** [comment]
Just take an image upscaler and upscale every BMP file in the data folder to 200%. Ideally, you'd want to redraw every sprite to actually make use of 2xRes.  
And for god's sake, whatever you do, _**DO NOT USE CAVE STORY+ GRAPHICS!!!**_

**Comment by Clownacy** [comment]
Oh right, this issue's still open. To be clear, you can use Cave Story+'s graphics if you want. I do it all the time. Just don't put them in a mod you're gonna give away or anything. Copyright laws and all.
